language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get install -qq samtools
    - sudo apt-get install -qq bwa

install: "python setup.py install"

script: "python ProDuSe/adapter_predict.py -i test/test5/wv_R1.fastq test/test5/wv_R2.fastq"
